package CritterRush.view;
import java.awt.Color;


public class CreditsPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;
	private TowerDefenseGame TDG;
        
    public CreditsPanel(TowerDefenseGame frame, boolean visibility) {
        initComponents();
        this.TDG = frame;
        
        setBackground(Color.BLACK);
		this.setDoubleBuffered(true);
		this.setVisible(visibility);
		this.setFocusable(true);
		this.requestFocus(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        creditsText = new javax.swing.JTextField();
        nadineLabel = new javax.swing.JLabel();
        joeyLabel = new javax.swing.JLabel();
        dylanLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 15));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setLayout(null);

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/back unpressed.png"))); // NOI18N
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.setDefaultCapable(false);
        backButton.setFocusable(false);
        backButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/back pressed.png"))); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(15, 18, 138, 46);

        creditsText.setBackground(new java.awt.Color(0, 0, 0));
        creditsText.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        creditsText.setForeground(new java.awt.Color(255, 255, 255));
        creditsText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        creditsText.setText("Critter Rush v1.0");
        creditsText.setBorder(null);
        creditsText.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        creditsText.setMargin(new java.awt.Insets(0, 0, 0, 0));
        creditsText.setOpaque(false);
        creditsText.setRequestFocusEnabled(false);
        creditsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsTextActionPerformed(evt);
            }
        });
        add(creditsText);
        creditsText.setBounds(350, 260, 250, 60);

        nadineLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nadineLabel.setForeground(new java.awt.Color(255, 255, 255));
        nadineLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nadineLabel.setText("Nadine Bou Khzam");
        add(nadineLabel);
        nadineLabel.setBounds(380, 340, 200, 50);

        joeyLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        joeyLabel.setForeground(new java.awt.Color(255, 255, 255));
        joeyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        joeyLabel.setText("Joey Kazma");
        add(joeyLabel);
        joeyLabel.setBounds(410, 310, 130, 50);

        dylanLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dylanLabel.setForeground(new java.awt.Color(255, 255, 255));
        dylanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dylanLabel.setText("Dylan Andrianantenaina");
        add(dylanLabel);
        dylanLabel.setBounds(360, 370, 240, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        TDG.panelSwap(TowerDefenseGame.creditsPanel, TowerDefenseGame.mainMenuPanel);
        
    }//GEN-LAST:event_backButtonActionPerformed

    private void creditsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditsTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField creditsText;
    private javax.swing.JLabel dylanLabel;
    private javax.swing.JLabel joeyLabel;
    private javax.swing.JLabel nadineLabel;
    // End of variables declaration//GEN-END:variables
}
