package CritterRush.view;
import java.awt.Color;


public class CreditsPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;
	private TowerDefenseGame TDG;
        
    public CreditsPanel(TowerDefenseGame frame, boolean visibility) {
        initComponents();
        this.TDG = frame;
        
        setBackground(Color.BLACK);
	this.setDoubleBuffered(true);
	this.setVisible(visibility);
	this.setFocusable(true);
	this.requestFocus(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        backButton = new javax.swing.JButton();
        creditsText = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 15));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.GridBagLayout());

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/back unpressed.png"))); // NOI18N
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.setDefaultCapable(false);
        backButton.setFocusable(false);
        backButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/back pressed.png"))); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(backButton, gridBagConstraints);

        creditsText.setBackground(new java.awt.Color(0, 0, 0));
        creditsText.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        creditsText.setForeground(new java.awt.Color(255, 255, 255));
        creditsText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        creditsText.setText("Critter Rush v1.0");
        creditsText.setBorder(null);
        creditsText.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        creditsText.setMargin(new java.awt.Insets(0, 0, 0, 0));
        creditsText.setOpaque(false);
        creditsText.setRequestFocusEnabled(false);
        creditsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsTextActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 750;
        gridBagConstraints.ipady = 550;
        add(creditsText, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        TDG.panelSwap(TDG.creditsPanel, TDG.mainMenuPanel);
        
    }//GEN-LAST:event_backButtonActionPerformed

    private void creditsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditsTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField creditsText;
    // End of variables declaration//GEN-END:variables
}
