package CritterRush.view;


import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

import CritterRush.model.ToolBox;
import CritterRush.controller.ICManager;
import CritterRush.controller.MapManager;



public class EditorPanel extends javax.swing.JPanel{

	private static final long serialVersionUID = 1L;
	private TowerDefenseGame TDG;

    /**
     * Creates new form EditorPanel
     */
    public EditorPanel(TowerDefenseGame frame, boolean visibility) {
        initComponents();
        
        this.TDG = frame;
        
        setBackground(new java.awt.Color(255, 204, 153));
		setDoubleBuffered(true);
		setVisible(visibility);
		this.setFocusable(true);
		this.requestFocus(true);
    }
    
     @Override
    public void paintComponent(Graphics g) {
    	super.paintComponent(g);
        MapManager.getEditorMap().draw(g);
        ToolBox.draw(g);
    }
    
    /**
     * Take a screenshot of the map to be used as an icon.
     */
    public void mapScreenShot(){
		BufferedImage bufImage = new BufferedImage(ICManager.fieldSizeX,
				ICManager.fieldSizeY, BufferedImage.TYPE_INT_RGB);
		this.paint(bufImage.createGraphics());
		File imageFile = new File("resources/map" +  String.valueOf(MapManager.getMapCount()) + ".png");

		BufferedImage resized = new BufferedImage(195, 150,
				bufImage.TYPE_INT_RGB);

		// Paint scaled version of image to new image

		Graphics2D graphics2D = resized.createGraphics();
		graphics2D.setRenderingHint(RenderingHints.KEY_INTERPOLATION,
				RenderingHints.VALUE_INTERPOLATION_BILINEAR);
		graphics2D.drawImage(bufImage, 0, 0, 195, 150, null);

		// clean up
		graphics2D.dispose();
		ICManager.maps[MapManager.getMapCount()] = new ImageIcon(resized);

		try {
			imageFile.createNewFile();
			ImageIO.write(resized, "png", imageFile);
		} catch (Exception ex) {
		}
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        textureTool = new javax.swing.JRadioButton();
        spawnTool = new javax.swing.JRadioButton();
        done = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        editorToolsTitle = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 153));
        setForeground(new java.awt.Color(255, 204, 153));
        setMaximumSize(new java.awt.Dimension(960, 600));
        setPreferredSize(new java.awt.Dimension(960, 600));

        buttonGroup1.add(textureTool);
        textureTool.setSelected(true);
        textureTool.setText("Texture Tool");
        textureTool.setContentAreaFilled(false);
        textureTool.setFocusable(false);
        textureTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textureToolActionPerformed(evt);
            }
        });

        buttonGroup1.add(spawnTool);
        spawnTool.setText("Spawn Tool");
        spawnTool.setContentAreaFilled(false);
        spawnTool.setFocusable(false);
        spawnTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spawnToolActionPerformed(evt);
            }
        });

        done.setText("Done");
        done.setMaximumSize(new java.awt.Dimension(60, 25));
        done.setMinimumSize(new java.awt.Dimension(60, 25));
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.setMaximumSize(new java.awt.Dimension(60, 25));
        cancel.setMinimumSize(new java.awt.Dimension(60, 25));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        editorToolsTitle.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        editorToolsTitle.setText("Editor Tools");
        editorToolsTitle.setBorder(null);
        editorToolsTitle.setCaretColor(new java.awt.Color(204, 51, 0));
        editorToolsTitle.setFocusable(false);
        editorToolsTitle.setOpaque(false);
        editorToolsTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editorToolsTitleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(804, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textureTool)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cancel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(done, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spawnTool, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(editorToolsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(editorToolsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textureTool)
                .addGap(18, 18, 18)
                .addComponent(spawnTool)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addComponent(done, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void spawnToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spawnToolActionPerformed
        ToolBox.setCurrentTool(ToolBox.getSpawnTool());
    }//GEN-LAST:event_spawnToolActionPerformed
    
    private void textureToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textureToolActionPerformed
        ToolBox.setCurrentTool(ToolBox.getTextureTool());
    }//GEN-LAST:event_textureToolActionPerformed

    private void editorToolsTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editorToolsTitleActionPerformed
        //Nothing to do here
    }//GEN-LAST:event_editorToolsTitleActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
    	MapManager.setSelectedMap(null);
    	MapManager.resetEditorMap();
        TDG.panelSwap(TDG.editorPanel, TDG.mapSelectionPanel);
        
    }//GEN-LAST:event_cancelActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
    	
    	if(MapManager.getEditorMap().checkValidity() == true){
    		MapManager.addMap(MapManager.getEditorMap());
    		mapScreenShot();
        	MapManager.setSelectedMap(null);
        	MapManager.resetEditorMap();
        	TDG.mapSelectionPanel.updateMapIcons();
        	TDG.panelSwap(TDG.editorPanel, TDG.mapSelectionPanel);
    	}
    	else {
    		TDG.printMessage("Current map setup is invalid.");
    	}
    	
    }//GEN-LAST:event_doneActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel;
    private javax.swing.JButton done;
    private javax.swing.JTextField editorToolsTitle;
    private javax.swing.JRadioButton spawnTool;
    private javax.swing.JRadioButton textureTool;
    // End of variables declaration//GEN-END:variables
}
