
package CritterRush.view;

import java.awt.Color;



public class MainMenuPanel extends javax.swing.JPanel {

    private TowerDefenseGame TDG;
   
    public MainMenuPanel(TowerDefenseGame frame, boolean visibility) {
        initComponents();
        this.TDG = frame;
        
        setBackground(Color.BLACK);
		setDoubleBuffered(true);
		setVisible(visibility);
		this.setFocusable(true);
		this.requestFocus(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        playButton = new javax.swing.JButton();
        creditsButton = new javax.swing.JButton();
        GameTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(960, 600));
        setPreferredSize(new java.awt.Dimension(960, 600));
        setLayout(new java.awt.GridBagLayout());

        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/Play button unpressed.png"))); // NOI18N
        playButton.setBorderPainted(false);
        playButton.setContentAreaFilled(false);
        playButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        playButton.setDefaultCapable(false);
        playButton.setFocusable(false);
        playButton.setHideActionText(true);
        playButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/Play button pressed.png"))); // NOI18N
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(playButton, gridBagConstraints);

        creditsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/credits unpressed.png"))); // NOI18N
        creditsButton.setBorderPainted(false);
        creditsButton.setContentAreaFilled(false);
        creditsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        creditsButton.setFocusable(false);
        creditsButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/credits pressed.png"))); // NOI18N
        creditsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(creditsButton, gridBagConstraints);

        GameTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CritterRushTitle.png"))); // NOI18N
        GameTitle.setAlignmentY(0.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(-50, 0, 80, 0);
        add(GameTitle, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        TDG.panelSwap(TDG.mainMenuPanel, TDG.mapSelectionPanel);
    }//GEN-LAST:event_playButtonActionPerformed

    private void creditsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsButtonActionPerformed
        TDG.panelSwap(TDG.mainMenuPanel, TDG.creditsPanel);
    }//GEN-LAST:event_creditsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GameTitle;
    private javax.swing.JButton creditsButton;
    private javax.swing.JButton playButton;
    // End of variables declaration//GEN-END:variables
}
