package CritterRush.view;

import java.awt.Color;

import javax.swing.JLabel;
import javax.swing.JRadioButton;

import CritterRush.controller.GameController;
import CritterRush.controller.ICManager;
import CritterRush.controller.MapManager;
import CritterRush.model.tools.EditorTools;

public class MapSelectionPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;
	private TowerDefenseGame TDG;
    private JRadioButton[] rButtons;
    private JLabel[] mapLabels;
    
    public MapSelectionPanel(TowerDefenseGame frame, boolean visibility) {
        initComponents();
        this.TDG = frame;
        
        setBackground(Color.BLACK);
		setDoubleBuffered(true);
		setVisible(visibility);
		this.setFocusable(true);
		this.requestFocus(true);
		
		mapLabels = new JLabel[] {Map1,Map2,Map3,Map4};
        rButtons = new JRadioButton[] {defaultMapButton, map2Button, map3Button, map4Button};
        
        updateMapIcons();
    }
    
    //set map Icons
    public void updateMapIcons(){
    	mapLabels[0].setIcon(ICManager.maps[0]);
    	for (int i = 2; i < MapManager.getMaxCount() + 1; i++){
    		if(i <= MapManager.getMapCount()){
    			mapLabels[i - 1].setIcon(ICManager.maps[i-1]);
    			rButtons[i - 1].setEnabled(true);
    			
    		}
    		else{
    			mapLabels[i - 1].setIcon(new javax.swing.ImageIcon(getClass().getResource("/map/empty.png")));
    			rButtons[i - 1].setEnabled(false);
    		}
    	}	
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        backButton = new javax.swing.JButton();
        Map1 = new javax.swing.JLabel();
        defaultMapButton = new javax.swing.JRadioButton();
        map2Button = new javax.swing.JRadioButton();
        Map2 = new javax.swing.JLabel();
        map3Button = new javax.swing.JRadioButton();
        map4Button = new javax.swing.JRadioButton();
        Map3 = new javax.swing.JLabel();
        Map4 = new javax.swing.JLabel();
        createMapButton = new javax.swing.JButton();
        deleteMapButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(null);

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/back unpressed.png"))); // NOI18N
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.setDefaultCapable(false);
        backButton.setFocusable(false);
        backButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/back pressed.png"))); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(20, 20, 138, 46);

        Map1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Map1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/map/empty.png"))); // NOI18N
        add(Map1);
        Map1.setBounds(50, 140, 215, 200);

        buttonGroup1.add(defaultMapButton);
        defaultMapButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        defaultMapButton.setForeground(new java.awt.Color(255, 255, 255));
        defaultMapButton.setText("Default Map");
        defaultMapButton.setContentAreaFilled(false);
        defaultMapButton.setFocusable(false);
        defaultMapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultMapButtonActionPerformed(evt);
            }
        });
        add(defaultMapButton);
        defaultMapButton.setBounds(100, 350, 130, 25);

        buttonGroup1.add(map2Button);
        map2Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        map2Button.setForeground(new java.awt.Color(255, 255, 255));
        map2Button.setText("Custom Map 1");
        map2Button.setContentAreaFilled(false);
        map2Button.setFocusable(false);
        map2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                map2ButtonActionPerformed(evt);
            }
        });
        add(map2Button);
        map2Button.setBounds(310, 350, 150, 25);

        Map2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Map2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/map/empty.png"))); // NOI18N
        add(Map2);
        Map2.setBounds(270, 140, 215, 200);

        buttonGroup1.add(map3Button);
        map3Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        map3Button.setForeground(new java.awt.Color(255, 255, 255));
        map3Button.setText("Custom Map 2");
        map3Button.setContentAreaFilled(false);
        map3Button.setFocusable(false);
        map3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                map3ButtonActionPerformed(evt);
            }
        });
        add(map3Button);
        map3Button.setBounds(530, 350, 130, 25);

        buttonGroup1.add(map4Button);
        map4Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        map4Button.setForeground(new java.awt.Color(255, 255, 255));
        map4Button.setText("Custom Map 3");
        map4Button.setContentAreaFilled(false);
        map4Button.setFocusable(false);
        map4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                map4ButtonActionPerformed(evt);
            }
        });
        add(map4Button);
        map4Button.setBounds(730, 350, 150, 25);

        Map3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Map3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/map/empty.png"))); // NOI18N
        add(Map3);
        Map3.setBounds(480, 140, 215, 200);

        Map4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Map4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/map/empty.png"))); // NOI18N
        add(Map4);
        Map4.setBounds(700, 140, 215, 200);

        createMapButton.setText("Create Map");
        createMapButton.setMaximumSize(new java.awt.Dimension(100, 50));
        createMapButton.setMinimumSize(new java.awt.Dimension(100, 50));
        createMapButton.setPreferredSize(new java.awt.Dimension(100, 50));
        createMapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMapButtonActionPerformed(evt);
            }
        });
        add(createMapButton);
        createMapButton.setBounds(107, 484, 100, 50);

        deleteMapButton.setText("Delete Map");
        deleteMapButton.setMaximumSize(new java.awt.Dimension(100, 50));
        deleteMapButton.setMinimumSize(new java.awt.Dimension(100, 50));
        deleteMapButton.setPreferredSize(new java.awt.Dimension(100, 50));
        deleteMapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMapButtonActionPerformed(evt);
            }
        });
        add(deleteMapButton);
        deleteMapButton.setBounds(322, 484, 100, 50);

        startButton.setText("Start");
        startButton.setMaximumSize(new java.awt.Dimension(100, 50));
        startButton.setMinimumSize(new java.awt.Dimension(100, 50));
        startButton.setPreferredSize(new java.awt.Dimension(100, 50));
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        add(startButton);
        startButton.setBounds(752, 484, 100, 50);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        background.setText("jLabel1");
        add(background);
        background.setBounds(0, 0, 960, 600);
    }// </editor-fold>//GEN-END:initComponents

    //Swing control functions
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        TDG.panelSwap(TowerDefenseGame.mapSelectionPanel, TowerDefenseGame.mainMenuPanel);
    }//GEN-LAST:event_backButtonActionPerformed

    private void defaultMapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultMapButtonActionPerformed
        MapManager.setSelectedMap(MapManager.getMap(1));
        //System.out.println("RETARD");
    }//GEN-LAST:event_defaultMapButtonActionPerformed
    
    private void map2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_map2ButtonActionPerformed
    	MapManager.setSelectedMap(MapManager.getMap(2));
    }//GEN-LAST:event_map2ButtonActionPerformed

    private void map3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_map3ButtonActionPerformed
    	MapManager.setSelectedMap(MapManager.getMap(3));
    }//GEN-LAST:event_map3ButtonActionPerformed
    
    private void map4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_map4ButtonActionPerformed
    	MapManager.setSelectedMap(MapManager.getMap(4));
    }//GEN-LAST:event_map4ButtonActionPerformed

    private void createMapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMapButtonActionPerformed
        if(MapManager.getMapCount() < MapManager.getMaxCount()){
            TDG.panelSwap(TowerDefenseGame.mapSelectionPanel, TowerDefenseGame.editorPanel);
        	EditorTools.setCurrentTool(EditorTools.getTextureTool());
        } else 
            TDG.printMessage("The maximum number of maps has been reached.");
    }//GEN-LAST:event_createMapButtonActionPerformed

    private void deleteMapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMapButtonActionPerformed
        if(MapManager.getSelectedMap() != null){
        	if(MapManager.getSelectedMap() == MapManager.getMap(1)){
        		TDG.printMessage("Cannot delete default map.");
        	}
        	else{
                MapManager.deleteMap(MapManager.getSelectedMap());
                MapManager.setSelectedMap(null);
                updateMapIcons();
                buttonGroup1.clearSelection();
        	}
        } else 
        	TDG.printMessage("No map selected.");
    }//GEN-LAST:event_deleteMapButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
    	if(MapManager.getSelectedMap() != null){
    		TowerDefenseGame.gamePanel.setGame(new GameController());
    		TowerDefenseGame.gamePanel.getGame().setObserver(TowerDefenseGame.gamePanel);
    		TowerDefenseGame.gamePanel.reset();
    		TDG.panelSwap(TowerDefenseGame.mapSelectionPanel, TowerDefenseGame.gamePanel);
    		
    	}else 
    		TDG.printMessage("No map selected.");
    }//GEN-LAST:event_startButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Map1;
    private javax.swing.JLabel Map2;
    private javax.swing.JLabel Map3;
    private javax.swing.JLabel Map4;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton createMapButton;
    private javax.swing.JRadioButton defaultMapButton;
    private javax.swing.JButton deleteMapButton;
    private javax.swing.JRadioButton map2Button;
    private javax.swing.JRadioButton map3Button;
    private javax.swing.JRadioButton map4Button;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
